In [1]:
import numpy as np
import random

# Basic Blackjack Strategy Function

### Not using this for the Monte-carlo Evaluation

In [4]:
BlackJackStrategy([6,5], 1)

'Hit'

# Value Function
3 dimensional array, where first index is \[cardsum(12 to 21) - 12\] (_for indexing_); second index is 0 if no usable ace and 1 if any; third index is dealer card \[(1 to 10)-1\](_for indexing_).

In [2]:
V = np.array([[[0.]*10]*2]*10)

In [3]:
V

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.,

# BlackJack Dynamic Programming Strategy

In [4]:
states = []
for i in range(10):
    for j in range(2):
        for k in range(10):
            states.append((i, j, k))
states

[(0, 0, 0),
 (0, 0, 1),
 (0, 0, 2),
 (0, 0, 3),
 (0, 0, 4),
 (0, 0, 5),
 (0, 0, 6),
 (0, 0, 7),
 (0, 0, 8),
 (0, 0, 9),
 (0, 1, 0),
 (0, 1, 1),
 (0, 1, 2),
 (0, 1, 3),
 (0, 1, 4),
 (0, 1, 5),
 (0, 1, 6),
 (0, 1, 7),
 (0, 1, 8),
 (0, 1, 9),
 (1, 0, 0),
 (1, 0, 1),
 (1, 0, 2),
 (1, 0, 3),
 (1, 0, 4),
 (1, 0, 5),
 (1, 0, 6),
 (1, 0, 7),
 (1, 0, 8),
 (1, 0, 9),
 (1, 1, 0),
 (1, 1, 1),
 (1, 1, 2),
 (1, 1, 3),
 (1, 1, 4),
 (1, 1, 5),
 (1, 1, 6),
 (1, 1, 7),
 (1, 1, 8),
 (1, 1, 9),
 (2, 0, 0),
 (2, 0, 1),
 (2, 0, 2),
 (2, 0, 3),
 (2, 0, 4),
 (2, 0, 5),
 (2, 0, 6),
 (2, 0, 7),
 (2, 0, 8),
 (2, 0, 9),
 (2, 1, 0),
 (2, 1, 1),
 (2, 1, 2),
 (2, 1, 3),
 (2, 1, 4),
 (2, 1, 5),
 (2, 1, 6),
 (2, 1, 7),
 (2, 1, 8),
 (2, 1, 9),
 (3, 0, 0),
 (3, 0, 1),
 (3, 0, 2),
 (3, 0, 3),
 (3, 0, 4),
 (3, 0, 5),
 (3, 0, 6),
 (3, 0, 7),
 (3, 0, 8),
 (3, 0, 9),
 (3, 1, 0),
 (3, 1, 1),
 (3, 1, 2),
 (3, 1, 3),
 (3, 1, 4),
 (3, 1, 5),
 (3, 1, 6),
 (3, 1, 7),
 (3, 1, 8),
 (3, 1, 9),
 (4, 0, 0),
 (4, 0, 1),
 (4, 0, 2),
 (4,

In [6]:
dealer_dist = [
    [13.6, 5.6, 14.3, 14.6, 13.8, 38.1],
    [34.9, 13.6, 14.1, 12.8, 12.8, 11.9],
    [38.1, 11.8, 13.4, 12.6, 12.2, 12.0],
    [39.6, 11.9, 13.3, 12.1, 11.8, 11.4],
    [42.1, 12.1, 12.4, 11.0, 11.6, 10.9],
    [43.5, 12.3, 11.8, 11.0, 11.2, 10.3],
    [26.3, 37.0, 14.1, 7.9, 7.8, 7.0],
    [25.0, 12.7,35.6, 12.8, 7.3, 6.6],
    [22.3, 12.0, 12.0, 35.6, 11.9, 6.2],
    [21.3, 11.25, 11.5, 11.1, 34.1, 11.3]
]

# cumulative win probability
# sum of all indexes before
for probabilities in dealer_dist:
    for i in range(1, 6):
        probabilities[i] += probabilities[i-1]
        
dealer_dist

[[13.6, 19.2, 33.5, 48.1, 61.900000000000006, 100.0],
 [34.9, 48.5, 62.6, 75.4, 88.2, 100.10000000000001],
 [38.1,
  49.900000000000006,
  63.300000000000004,
  75.9,
  88.10000000000001,
  100.10000000000001],
 [39.6, 51.5, 64.8, 76.89999999999999, 88.69999999999999, 100.1],
 [42.1, 54.2, 66.60000000000001, 77.60000000000001, 89.2, 100.10000000000001],
 [43.5, 55.8, 67.6, 78.6, 89.8, 100.1],
 [26.3, 63.3, 77.39999999999999, 85.3, 93.1, 100.1],
 [25.0, 37.7, 73.30000000000001, 86.10000000000001, 93.4, 100.0],
 [22.3, 34.3, 46.3, 81.9, 93.80000000000001, 100.00000000000001],
 [21.3, 32.55, 44.05, 55.15, 89.25, 100.55]]

In [7]:
def blackjack_probability(s_, s, a, r):
    stay = 0
    hit = 1
      
    
    if a == stay:
        '''find Probability of win, loss, tie'''
        if s[0] < 5:
            # probability dealer busts
            if r == 1:
                return (dealer_dist[s[2]][0])/100

            else:
                return (1 - dealer_dist[s[2]][0]/100)
        
        else:
            index = s[0] - 4      # 17 is 1
            if r == 1:
                return (dealer_dist[s[2]][index-1]/ 100)
            
            elif r == 0:
                return ((dealer_dist[s[2]][index] - dealer_dist[s[2]-1][index-1])/100)
            
            else:
                return (1-(dealer_dist[s[2]][index]/100))
                
    
    if a == hit:
        '''Find probability s_'''
        if s_[2] != s_[2]:
            '''dealer card is not the same'''
            return 0
        
        if s_ == (-1, -1, -1):
            '''find Probability of a bust'''
            return (4 + s[0])/13
            
        if s_[1] == 0 and s[1] == 1:
            '''player has to use his ace'''
            if s_[0] == s[0]:
                '''probability of a 10 value card'''
                return 4/13
            
            if s_[0] > s[0]:
                return 0
            
            return 1/13
        
        if s_[1] == s[1]:
            '''no ace transaction'''
            if s_[0] <= s[0]:
                '''new hand cannot be less than old hand'''
                return 0
        
        return 1/13

In [8]:
def pi_20(action, state):
    '''deterministic policy that returns the probability of action given state'''
    stay = 0
    hit = 1
    
    if state[0] >= 8:
        if action == stay:  
            return 1
        else:
            return 0
    else:
        if action == hit:
            return 0
        else:
            return 1

In [9]:
def evaluate_policy(V, theta):
    while True:
        delta = 0
        for s1, s2, s3 in states:
            v = V[s1][s2][s3]
            bellman_update(V, (s1, s2, s3))
            delta = max(delta, abs(v - V[s1][s2][s3]))
        if delta < theta:
            break
    return V

In [10]:
def bellman_update(V, state):
    """Mutate ``V`` according to the Bellman update equation."""
    stay = 0
    hit = 1
    
    hit_value = 0
    for s_ in states:
        Vs_ = V[s_[0]][s_[1]][s_[2]]
        hit_value += blackjack_probability(s_, state, hit, 0)*(0 + Vs_) 
    
    # probability of a bust
    hit_value += blackjack_probability((-1, -1, -1), state, hit, 0)*(-1 + 0) 
    
    # value of staying
    stay_value = 0
    for r in range(3):
        stay_value += blackjack_probability((-1, -1, -1), state, stay, (r-1))*(r-1)
    
    hand, ace, dealer = state
    V[hand][ace][dealer] = pi_20(1, state)*hit_value + pi_20(0, state)*stay_value
    return 

In [42]:
evaluate_poli

In [12]:
V

array([[[-0.728 , -0.302 , -0.238 , -0.208 , -0.158 , -0.13  , -0.474 ,
         -0.5   , -0.554 , -0.574 ],
        [-0.728 , -0.302 , -0.238 , -0.208 , -0.158 , -0.13  , -0.474 ,
         -0.5   , -0.554 , -0.574 ]],

       [[-0.728 , -0.302 , -0.238 , -0.208 , -0.158 , -0.13  , -0.474 ,
         -0.5   , -0.554 , -0.574 ],
        [-0.728 , -0.302 , -0.238 , -0.208 , -0.158 , -0.13  , -0.474 ,
         -0.5   , -0.554 , -0.574 ]],

       [[-0.728 , -0.302 , -0.238 , -0.208 , -0.158 , -0.13  , -0.474 ,
         -0.5   , -0.554 , -0.574 ],
        [-0.728 , -0.302 , -0.238 , -0.208 , -0.158 , -0.13  , -0.474 ,
         -0.5   , -0.554 , -0.574 ]],

       [[-0.728 , -0.302 , -0.238 , -0.208 , -0.158 , -0.13  , -0.474 ,
         -0.5   , -0.554 , -0.574 ],
        [-0.728 , -0.302 , -0.238 , -0.208 , -0.158 , -0.13  , -0.474 ,
         -0.5   , -0.554 , -0.574 ]],

       [[-0.728 , -0.302 , -0.238 , -0.208 , -0.158 , -0.13  , -0.474 ,
         -0.5   , -0.554 , -0.574 ],
        [-0

In [11]:
evaluation = evaluate_policy(V, 0.002)

# One Hand Blackjack Simulator

In [10]:
def blackjack_hand_result(V, visit_count):
    #Deck of cards, 4 types of 10
    
    deck=np.array([1,2,3,4,5,6,7,8,9,10,10,10,10])
    
    #Creating a random hand if none is input
    
    player_hand=[random.choice(deck), random.choice(deck)]
        
    dealer_card=random.choice(deck)
    
    # keeps track of all states that the hand has been in during one play
    states = []
    
    player_sum = sum(player_hand)
    
    # an ace that can be used as an 11 i.e. the sum of the cards is less than 12
    usable_ace = 0
    if 1 in player_hand:
        usable_ace = 1
        player_sum += 10
    
    
    if player_sum > 11:
        states.append((player_sum-12, usable_ace, dealer_card-1))
        visit_count[player_sum-12][usable_ace][dealer_card-1] += 1
        
    # keeps track of dealers hand
    dealer_cards=[dealer_card]
    

    # Seeing if player hit blackjack
    if player_sum == 21:

        #Seeing if casino also hit blackjack, in which case tie

        dealer_cards.append(random.choice(deck))
        if 1 in (dealer_cards) and sum(dealer_cards)==11:
            update_values(states, 0, V, visit_count)
            return 0
        
        update_values(states, 1, V, visit_count)
        return 1
    

    else:
    # Seeing how often it says to 'hit'

        while pi_20(player_hand, dealer_card) == 'Hit':
            #Adding one card for every hit
            new_card = random.choice(deck)
            player_hand.append(new_card)
            
            player_sum += new_card
            
            if new_card == 1 and player_sum < 12:
                usable_ace = 1
                player_sum += 10
            
            if usable_ace == 1 and player_sum > 21:
                player_sum -= 10
                usable_ace == 0

            #Player loses bet if hand goes above 21
            if player_sum>21:
                update_values(states, -1, V, visit_count)
                return -1
            
            if player_sum > 11:
                states.append((player_sum-12, usable_ace, dealer_card-1))
                visit_count[player_sum-12][usable_ace][dealer_card-1] += 1
            
    while True:
        #Plays out the blackjack hand from dealer's side

        #Give dealer extra card if loop hasn't broken
        dealer_cards.append(random.choice(deck))


        #Keep track of sum of dealer's cards
        dealer_score= sum(dealer_cards)

        #Keep track of soft score if dealer has an ace

        soft_score= dealer_score
        if dealer_score<=11 and 1 in dealer_cards:
            soft_score+=10

        #If dealer gets blackjack you lose even if you have 21
        if len(dealer_cards)==2 and soft_score==21:
            return -1
        
        #Dealer stays on all 17s
        if soft_score>=17:

            #If dealer bust, player wins bet
            if soft_score>21:
                update_values(states, 1, V, visit_count)
                return 1

            #If player has more than dealer, player wins bet
            if player_sum>soft_score:
                update_values(states, 1, V, visit_count)
                return 1

            #Tie means no money changes hands
            if player_sum==soft_score:
                update_values(states, 0, V, visit_count)
                return 0

            #If player has lower, player loses bet
            if player_sum<soft_score:
                update_values(states, -1, V, visit_count)
                return -1


# Multiple Hand Sim, Test to see house edge in Blackjack

In [11]:
def blackjack_sim(n_hands, V, visit_count):
    for i in range(n_hands):
        blackjack_hand_result(V, visit_count)
     

In [41]:
blackjack_sim(50_000, V, visit_count)
V

array([[[-0.26405388, -0.15314044, -0.13846154, -0.10302594,
         -0.10444444, -0.04515174, -0.22066421, -0.26472782,
         -0.27233429, -0.26165185],
        [-0.25580475, -0.21495327, -0.16666667, -0.15662651,
          0.05102041, -0.07207207, -0.2375    , -0.18292683,
         -0.17045455, -0.21351226]],

       [[-0.26442631, -0.17375093, -0.15884194, -0.13566206,
         -0.07035573, -0.03779289, -0.26539101, -0.24193548,
         -0.29933665, -0.27137281],
        [-0.31260144, -0.2247191 , -0.05882353, -0.12426036,
         -0.08433735, -0.03825137, -0.26701571, -0.22162162,
         -0.24022346, -0.21893254]],

       [[-0.26683922, -0.11769547, -0.12177778, -0.1112069 ,
         -0.07308684, -0.08485857, -0.21083827, -0.2278275 ,
         -0.29713293, -0.2629072 ],
        [-0.26744379, -0.15508021, -0.2       , -0.125     ,
         -0.05291005, -0.1027027 , -0.30167598, -0.28645833,
         -0.30097087, -0.21817141]],

       [[-0.26260742, -0.15789474, -0.13570128

In [46]:
import plotly.express as px

fig = px.imshow(without_ace)
fig.show()
without_ace

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

In [70]:
without_ace

[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]

In [58]:
with_ace = [[0.]*10]*10
for i in range(len(V)):
    for j in range(len(V[0][0])):
         with_ace[i][j] = V[i][1][j]

In [69]:
without_ace = [[0.]*10]*10
for i in range(len(V)):
    for j in range(len(V[0][0])):
         without_ace[i][j] = V[i][0][j]

In [11]:
#Simulates a million hands to estimate house edge
house_edge=-100*(blackjack_sim(n_hands=1_000_000, bet=1) / 1_000_000)
house_edge #percentage

TypeError: blackjack_sim() got an unexpected keyword argument 'bet'

# Strategy Test: Double 7 vs 6

In [10]:
#Player profit from following basic strategy
blackjack_sim(n_hands=100_000, player_h=[4,3], dealer_c=6, bet=1)


2104

In [11]:
blackjack_sim(n_hands=100_000, player_h=[4,3], dealer_c=6, bet=1, hard_c='Double')


-14626

# Strategy Test: Split 10s vs 6

In [12]:
blackjack_sim(n_hands=100_000, player_h=[10,10], dealer_c=6, bet=1)


70626

In [13]:
blackjack_sim(n_hands=100_000, player_h=[10,10], dealer_c=6, bet=1, hard_c='Split')


60517.5